name: Publish

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  id-token: write # Required for provenance

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: neuro-game-api
      url: https://npmjs.com/package/neuro-game-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.1

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm --filter=neuro-game-api publish
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
