name: Publish SDK + API

on:
  push:
    tags:
      - v*
      
permissions:
      contents: read
      id-token: write
      
jobs:
      changeset:
        name: Changesets
        runs-on: ubuntu-latest
      sdk:
          name: Build client SDK
          runs-on: ubuntu-latest
          steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            
          - name: Setup pnpm
            uses: pnpm/action-setup@v4
            
          - name: Setup Node.js
            uses: actions/setup-node@v5
            with:
              node-version: 22.14.0
              cache: 'pnpm'
              cache-dependency-path: './pnpm-lock.yaml'
              
          - name: Install deps
            run: pnpm install --frozen-lockfile
              
          - name: Publish SDK
            run: pnpm sdk publish
      api:
        name: Build server API
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
                  
          - name: Setup pnpm
            uses: pnpm/action-setup@v4
                  
          - name: Setup Node.js
            uses: actions/setup-node@v5
            with:
              node-version: 22.14.0
              cache: 'pnpm'
              cache-dependency-path: './pnpm-lock.yaml'
                    
          - name: Install deps
            run: pnpm install --frozen-lockfile
                    
          - name: Publish API
            run: pnpm api publish